### ISSUE TITLE
Devops team additions

### ISSUE THREAD

**Issue by realcodywburns** [ethereumclassic/DevOps#4]
to: @ethereumclassic/all-hands 
re: adding members to devops team

devops team members have write access to this repo as well as administrative access to the ethereumclassic tools listed in readme

with no objections, looking to add @tzdybal & @whilei

**Comment by kimisan** [comment]
Good to see it .
Please go ahead!

**Comment by OmniEdge** [comment]
ACK

**Comment by realcodywburns** [comment]
no objections after 7 days, closing and adding to team
